openapi: 3.0.3
info:
  title: Unidash API
  version: 1.0.0
  description: API документация для Unidash
servers:
  - url: http://localhost:8080/api/v1
paths:
  /ping:
    get:
      summary: Проверка доступности сервера
      responses:
        '200':
          description: OK